apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-host
  namespace: {PROJECT_NAMESPACE}
data:
  # http://<pod名称>.<容器名>:<容器端口>
  registry_url: http://{PROJECT_NAME}-0.{PROJECT_NAME}:{PROJECT_PORT}/eureka/,http://{PROJECT_NAME}-2.{PROJECT_NAME}:{PROJECT_PORT}/eureka/,http://{PROJECT_NAME}-3.{PROJECT_NAME}:{PROJECT_PORT}/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: {PROJECT_NAME}
  namespace: {PROJECT_NAMESPACE}
  labels:
    app: {PROJECT_NAME}
spec:
  type: NodePort
  selector:
    app: {PROJECT_NAME}
  ports:
    - port: {PROJECT_PORT}
      name: {PROJECT_NAME}
      targetPort: {PROJECT_PORT}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {PROJECT_NAME}
  namespace: {PROJECT_NAMESPACE}
spec:
  replicas: 3
  serviceName: {PROJECT_NAME}
  selector:
    matchLabels: # 匹配下方的template中定义的label
      app: {PROJECT_NAME}
  template:
    metadata:
      labels:
        app: {PROJECT_NAME}
    spec:
      containers:
        - name: {PROJECT_NAME}
          image: {PROJECT_IMAGE}
          ports:
            - containerPort: {PROJECT_PORT}
          env:
            - name: EUREKA_HOST
              value: "{PROJECT_PORT}"
            - name: SERVER_NAME
              value: {PROJECT_NAME}
            - name: FETCH_EUREKA
              value: "true"
            - name: REGISTER_EUREKA
              value: "true"
            - name: EUREKA_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-host
                  key: registry_url
